jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '19'
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SECRET_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.NEXUS_PASSWORD }}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.NEXUS_USERNAME }}
      name: Publish with Gradle
      run: ./gradlew publishToSonatype --no-daemon -Psign -PbuildProfile=experimental
name: Experimental Build
on:
  repository_dispatch:
    types: trigger-ga___experimental.yml
